### ISSUE TITLE
VarUInt read() example is incorrect

### ISSUE THREAD

**Issue by pluick** [TinyVG/specification#26] opened 2021-12-26 04:32 UTC
If I understand the VarUInt spec correctly, the 7th bit is set to indicate that this is the final bit of data. The example read() function seems to indicate the opposite (7th bit unset indicates the final bit). The example code should change from 0 -> 1, e.g.

    if ((byte & 0x80) == 0)
        break;

change to

    if ((byte & 0x80) == 1)
        break;

**Comment by ikskuh** [comment] 2021-12-26 09:07
No, the VarUInt function is correct, what is the problem is my bad description of that decoding and a typo. The last byte must have 0x0? as the upper byte, not 0x8?


Also, your new code here is definitly wrong, and you should use 0x80 in the comparison
```
if ((byte & 0x80) == 0x80) // 1 is never a possible value here!
    break;
```

**Comment by pluick** [comment] 2021-12-26 23:52
Oops, you are right about the bitmask.

So I was reading the description wrong and the changes should be something like this?:

    -Bytes are read until the uppermost bit in the byte is set
    +Bytes are read until the uppermost bit in the byte is not set

and about the final byte:

    -This byte must always have the uppermost 4 bits set as 0b1000????.
    +This byte must always have the uppermost 4 bits set as 0b0000????.

**Comment by ikskuh** [comment] 2021-12-27 08:37
yep, that is correct

**Comment by ikskuh** [comment] 2022-01-03 09:22
This should be fixed now

**Closed as completed by ikskuh** 2022-01-03 09:23 UTC
Labels: bug, documentation
